#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/storage/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"

storage_paths_cmd() {
  declare desc="List available paths"
  local cmd="storage:paths"
  local passed_phases=(deploy run)
  local storage_path=${DOKKU_LIB_ROOT}/data/storage/
  echo "Available paths in $storage_path"
  ls -lart $storage_path
}

storage_paths_cmd "$@"